### ISSUE TITLE
Use macros for module registration

### ISSUE THREAD

**Issue by Michael-F-Bryan** [nickbabcock/collectd-rust-plugin#1]
Just looking at the example on your README, it seems like you could benefit by hiding the module registration behind a macro. I did something similar for the [plugins section] of my Rust FFI guide, feel free to steal ideas from there :smile: 

So you could replace this:

```rust
#[no_mangle]
pub extern "C" fn module_register() {
    // The entry function for our plugin. Our registered read function will be called at
    // intervals defined by collectd
    let s = CString::new("myplugin").unwrap();
    unsafe {
        plugin_register_read(s.as_ptr(), Some(my_read));
    }
}
```

With something like this:

```rust
register_plugin!("myplugin", my_read);
```

Which may internally expand to:

```rust
#[no_mangle]
pub extern "C" fn module_register() {
  if let Ok(s) = CString::new("myplugin") {
    unsafe {
      plugin_register_read(s.as_ptr(), Some(my_read));
    }
  } 
}
```

[plugins section]: https://michael-f-bryan.github.io/rust-ffi-guide/dynamic_loading.html#setting-up-plugins

**Comment by nickbabcock** [comment]
Oh yes, that does look nice. Maybe I can pick your brain. Since `module_register` can create multiple hooks, how should one encapsulate them in a single macro call?

For instance, in the readme, `module_register` only registers the `plugin_register_read`, but in [`lib.rs`](https://github.com/nickbabcock/collectd-rust-plugin/blob/be61288adccc51c4fc44809ae52ff0c82e7740c7/src/lib.rs#L40-L48) I show an example of registering a config hook:

```rust
pub extern "C" fn module_register() {
    // snip ...
    unsafe {
        plugin_register_read(s.as_ptr(), Some(my_read));
        plugin_register_config(
            s.as_ptr(),
            Some(my_config),
            pointers.as_mut_ptr(),
            pointers.len() as i32,
        );
    }
}
```

In your ffi guide you mention using a trait, but I'm unsure how to represent the notion of "this plugin registers only a subset of the hooks"

**Comment by Michael-F-Bryan** [comment]
> Since module_register can create multiple hooks, how should one encapsulate them in a single macro call?

That sounds like a good idea. It'd be annoying if you needed to invoke the `register_plugin!()` macro after writing the definition of each and every plugin. I just had a second look at how plugins work and it seems like you do things by passing in a function pointer, which means any plugins which are "stateful" need to use globals. 

I was originally thinking you had control over the plugin registrar, meaning you could change its signature to use trait objects instead. Something that would allow nice things like carrying along state and having a `Drop` impl for cleanup at the end.

> In your ffi guide you mention using a trait, but I'm unsure how to represent the notion of "this plugin registers only a subset of the hooks"

In an ideal world, what I would do is define some `Plugin` trait which all traits must implement. You'd make sure each method can return a result, where one of the error variants is "not implemented" and then add a default impl for each method which says it's not implemented. 

```rust
enum Error {
  NotImplemented,
  ...
} 

pub trait Plugin {
  fn name(&self) -> &str;
  fn do_x(&mut self, some_arg: String) -> Result<(), Error> {
    Err(Error::NotImplemented)
  } 
  ...
}
```

In theory it'd be nice to say "this plugin can do X, Y, and Z" on registration, but that gets a bit complicated and doesn't really scale. The next best thing is to return a `NotImplemented` error and then either notify the user or continue on silently.

The reason I'm using a trait object instead of function pointers is they allow you to carry around state. They're also a lot more flexible because you can add methods and use them just like any other Rust trait object.

**Comment by nickbabcock** [comment]
Yes, wow thank you for the motivation and the guide! I was able to extract all the low level logic into a macro and made it general enough so that someday this can be become a crate on crates.io

It's far from perfect, but I ended up with a trait of:
```rust
pub trait Plugin {
    fn name(&self) -> &str;

    fn can_config(&self) -> bool;
    fn config_keys(&self) -> Vec<String>;
    fn config_callback(&mut self, key: String, value: String) -> Result<(), Error>;

    fn can_report(&self) -> bool;
    fn report_values(&self) -> Result<(), Error>;

    // More hooks will eventually be added
}
```

and if `can_config()` returns `false` then `config_keys` and `config_callback` can be `unimplemented!()`.

**Comment by Michael-F-Bryan** [comment]
Hmm, I'm not sure how I feel about the default impls for `config_keys` and `report_values` being to panic with `unimplemented!()`... A panic is usually reserved for errors which can't be recovered from and where the only logical solution is to crash loudly. It also feels like a bit of an antipattern to panic given you're also returning a `Result`. 

It seems like there's the implicit assumption that if `can_report` returns `false` then `return_values` will never be called and can therefore do whatever it wants. The problem is that temporal relationship (you call `can_report` first and only ask to report values if it returned `true`) isn't present anywhere except maybe as documentation. I'd prefer to drop the "can you do X?" method and instead return an `Error::NotImplemented`, although it sounds kinda like the look-before-you-leap vs easier-to-ask-permission argument. Both of which have their pros and cons.

**Comment by Michael-F-Bryan** [comment]
Hmm, I'm not sure how I feel about the default impls for `config_keys` and `report_values` being to panic with `unimplemented!()`... A panic is usually reserved for errors which can't be recovered from and where the only logical solution is to crash loudly. It also feels like a bit of an antipattern to panic given you're also returning a `Result`. 

It seems like there's the implicit assumption that if `can_report` returns `false` then `return_values` will never be called and can therefore do whatever it wants. The problem is that temporal relationship (you call `can_report` first and only ask to report values if it returned `true`) isn't present anywhere except maybe as documentation. I'd prefer to drop the "can you do X?" method and instead return an `Error::NotImplemented`, although it sounds kinda like the look-before-you-leap vs easier-to-ask-permission argument. Both of which have their pros and cons.

**Comment by nickbabcock** [comment]
Oh yes, I abhor the current design, but I didn't want to lose too much steam as I initially had something like this:

```rust
pub trait ConfigPlugin {
    fn config_keys(&self) -> Vec<String>;
    fn config_callback(&mut self, key: String, value: String) -> Result<(), Error>;
}

pub trait ReportPlugin {
    fn report_values(&self) -> Result<(), Error>;
}

pub trait Plugin {
    fn name(&self) -> &str;
    fn config(&self) -> Option<ConfigPlugin>;
    fn report(&self) -> Option<ReportPlugin>;
}
```

with a single impl, implementing all three traits with functions like

```rust
fn config(&self) -> Option<ConfigPlugin> {
    Some(self)
}
```

But I need a bit more time with the compiler to work out the proper design / solution

I thought about `Error::NotImplemented`, but I didn't want to register all the hooks only for execution to be a nop -- if a hook immediately returns `NotImplemented` it shouldn't even be registered (and it doesn't make sense to execute the hooks during registration to see if they implement `NotImplemented`

**Comment by Michael-F-Bryan** [comment]
What about adding a `capabilities()` method which returns a [bitflags] of all the available capabilities? That should allow you to discover what hooks are available.

[bitflags]: https://docs.rs/bitflags/1.0.1/bitflags/

**Comment by nickbabcock** [comment]
Oh another great idea! I'll also switch default implementation from a `unimplemented!()` panic to a more sensible error that you were alluding to. 😄

**Comment by nickbabcock** [comment]
After testing it out, I'm quite pleased with the current solution. Thank you so much for your advice and guidance. I'll close this issue as your original suggestion is now implemented.

The only thing remaining is the eyesore of:

```rust
lazy_static! {
    static ref PLUGIN: Mutex<MyPlugin> = Mutex::new(MyPlugin);
}

collectd_plugin!(PLUGIN);
```

There might be a way to register all the plugin hooks (including the config hook that modifies `MyPlugin`) without resorting mutable global -- but that can wait for a future release.

**Comment by Michael-F-Bryan** [comment]
Just out of curiosity, why do you need the `lazy_static!()`? Instead of passing the `collectd_plugin!()` macro an instance of a `Plugin`, I would have given it a constructor for something which implements `Plugin`  so you can create a new `Box<Plugin>` and gives ownership of it to whatever registration mechanism you use. That removes the `lazy_static!()` while also getting rid of the reliance on global state. 

I was thinking something along the lines of [this]. But that's just how I'd do things, it may not necessarily work for your scenario.

[this]: https://play.rust-lang.org/?gist=d762dbe9c929bd42961e98a87eba48bd&version=stable

**Comment by nickbabcock** [comment]
Let me take another crack at it after some rest 😄

**Comment by nickbabcock** [comment]
I'm stuck and I haven't progressed any further than:

```rust
macro_rules! collectd_plugin {
    ($constructor:path) => {
        #[no_mangle]
        pub extern "C" fn module_register() {
            let plugin = $constructor();

            if plugin.capabilities.has_read() {
                // plugin_register_read is a bindgen generated function
                // that requires signature of:
                // unsafe extern "C" fn(*const i8, *const i8) -> i32
                plugin_register_read(collectd_plugin_read)
            }

            // ...
        }

        unsafe extern fn collectd_plugin_read() -> std::os::raw::c_int {
            // Now how to access to access `plugin` without global
        }
    }
}
```

I can't seem to apply your example as `register_plugin` doesn't use the constructed plugin across multiple extern functions. So I'm not sure how to manage state across multiple extern functions without some sort of global declared.

**Comment by Michael-F-Bryan** [comment]
How is the plugin system for `collectd` designed? 

Usually I'd make it so the `extern "C"` registration function returns a boxed trait object and use that to encapsulate state, but if `collectd`'s plugin system requires you to give it bare function pointers and doesn't let you attach state (e.g. also provide a `void *` data pointer that gets given to your plugin whenever it's called) then it looks like your hands are tied :disappointed: 

Unfortunately the only way a bare function pointer can have state is if it uses static globals.

**Comment by nickbabcock** [comment]
> if `collectd`'s plugin system requires you to give it bare function pointers and doesn't let you attach state (e.g. also provide a void * data pointer that gets given to your plugin whenever it's called) then it looks like your hands are tied 😞

For all hooks there is an alternate function that essentially takes a `void*` pointer.  ... I think I have an inkling what you're going to say.

Let me get to work 😅

**Comment by nickbabcock** [comment]
Unfortunately configuration / initialization functions don't receive the `void*` created in the plugin register function:

```rust
// This global variable is only for the functions of config / init where we know that the
// function will be called only once from one thread. std::ptr::null_mut is not a const
// function on stable, so we inline the function body
static mut COLLECTD_PLUGIN_FOR_INIT: *mut $type = 0 as *mut $type; 
```

For the other functions, the `Box` pointer is given as an argument from collectd. Little annoying that I have to remember to `forget` the box pointer for those functions, else the plugin is dropped, but it's only minor.

**Comment by nickbabcock** [comment]
I think I'll close this. I ended up with something not too far from your design:

```rust
#[derive(Default)]
struct MyPlugin;

impl PluginManager for MyPlugin {
    fn name() -> &'static str {
        "myplugin"
    }

    fn plugins(_config: Option<&[ConfigItem]>) -> Result<PluginRegistration, Error> {
        Ok(PluginRegistration::Single(Box::new(MyPlugin)))
    }
}

impl Plugin for MyPlugin {
    fn capabilities(&self) -> PluginCapabilities {
        PluginCapabilities::READ
    }

    fn read_values(&mut self) -> Result<(), Error> {
        ValueListBuilder::new(Self::name(), "load")
            .values(&values)
            .submit()
    }
}

collectd_plugin!(MyPlugin);
```

Behind the scene it only needs a single mutable boolean 👌
